---
sidebar: sidebar
permalink: faq_fluid.html
keywords: faq, frequently asked questions, questions, fluid
summary: This FAQ can help if you’re just looking for a quick answer to a question.
---

= Frequently asked questions about Fluid
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This FAQ can help if you’re just looking for a quick answer to a question.

== What is Cloud Compliance?

Cloud Compliance is a cloud offering that uses Artificial Intelligence (AI) driven technology to help organizations understand data context and identify sensitive data across your storage systems. The systems can be Azure NetApp Files configurations, Cloud Volumes ONTAP systems hosted in AWS or Azure, Amazon S3 buckets, on-prem ONTAP systems, databases, and OneDrive accounts.
// non-NetApp file shares, generic S3 object storage,

Cloud Compliance provides pre-defined parameters (such as sensitive information types and categories) to address new data compliance regulations for data privacy and sensitivity, such as GDPR, CCPA, HIPAA, and more.

== Why should I use Fluid?

Fluid can simply and automatically enable you to build cloud like networks, deploy containers and virtual machines and create hybrid cloud architectures on any compute hardware:

* Comply with data compliance and privacy regulations.
* Comply with data retention policies.
* Easily locate and report on specific data in response to data subjects, as required by GDPR, CCPA, HIPAA, and other data privacy regulations.

== What are the common use cases for Fluid?

* Identify Personal Identifiable Information (PII).
* Identify a wide scope of sensitive information as required by GDPR and CCPA privacy regulations.
* Comply with new and upcoming data privacy regulations.

https://cloud.netapp.com/cloud-compliance[Learn more about the use cases for Cloud Compliance^].

== Which cloud providers are supported?

Fluid operates as part of Cloud Manager and currently supports AWS, Azure and Google. This provides your organization with truly unified hybrid, multi-cloud capabilities across different cloud providers.

== Which elastic connectivity providers are supported?

Fluid operates as part of Cloud Manager and currently supports:

* Console Connect by PCCW
* Megaport
* Equinix Fabric (formerly Equinix Cloud Exchange)

This provides your organization with truly unified hybrid, multi-cloud networking capabilities across different cloud providers and locations.

== How do I access Fluid?

Fluid is operated and managed through Cloud Manager. You can access Fluid features from the *Fluid* tab in Cloud Manager.

== How does Fluid work?

Cloud Compliance deploys another layer of Artificial Intelligence alongside your Cloud Manager system and storage systems. It then scans the data on volumes, buckets, databases, and OneDrive accounts and indexes the data insights that are found.

link:concept_cloud_compliance.html[Learn more about how Cloud Compliance works^].

== How much does Fluid cost?

The cost to use FLUID depends on the number of nodes you have in your deployment. A node is defined as a compute, switch or network function virtualisation (NFV) device. A subscription is required to deploy FLUID and connect the deployed clusters to Cloud Manager. See https://cloud.fluidhq.io/pricing[pricing^] for details.
+
link:task_deploy_cloud_compliance.html#subscribing-to-the-cloud-compliance-service[Learn how to subscribe^].
+
*Note:* This subscription is not needed during the Beta version period.
*Note:* Cloud provider and elastic connectivity charges are .

== What type of hardware is required for Fluid?

* For compute nodes, Fluid runs on any x86 server hardware with at least one internal disk drive, 2 network ports and 1 management network port

* For network switch nodes, Fluid runs on most "whitebox" hardware vendors that support Switchdev from the linux Kernel.

link:concept_cloud_compliance.html[Learn more about how Cloud Compliance works^].

== Does Fluid provide management of Kubernetes environments and workloads?

No - Fluid is designed to bridge the gap between bare-metal hardware and a running Kubernetes cluster. Fluid provides a kubeconfig file for download from the Cloud Manager interface which may then be imported into Kubernetes management tools such as Rancher, Google Anthos, Google GKE in GCP console, Red Hat OpenShift and many more.

== Which container and virtual machine types are supported?

Cloud Compliance scans all files for category and metadata insights and displays all file types in the file types section of the dashboard.

When Cloud Compliance detects Personal Identifiable Information (PII), or when it performs a DSAR search, only the following file formats are supported:
.PDF, .DOCX, .DOC, .PPTX, .XLS, .XLSX, .CSV, .TXT, .RTF, and .JSON.

== How do I enable Cloud Compliance?

First you need to deploy an instance of Cloud Compliance in Cloud Manager. Once the instance is running, you can enable it on existing working environments and databases from the *Compliance* tab or by selecting a specific working environment.

link:task_getting_started_compliance.html[Learn how to get started^].

NOTE: Activating Cloud Compliance results in an immediate initial scan. Compliance results display shortly after.

== How do I disable Cloud Compliance?

You can disable Cloud Compliance from the Canvas page after you select an individual working environment, database, or OneDrive account.

link:task_managing_compliance.html[Learn more^].

NOTE: To completely remove the Cloud Compliance instance, you can manually remove the Cloud Compliance instance from your cloud provider's portal.

== What happens if data tiering is enabled on Cloud Volumes ONTAP?

You might want to enable Cloud Compliance on a Cloud Volumes ONTAP system that tiers cold data to object storage. If data tiering is enabled, Cloud Compliance scans all of the data--data that's on disks and cold data tiered to object storage.

The compliance scan doesn't heat up the cold data--it stays cold and tiered to object storage.

== Can I use Cloud Compliance to scan on-premises ONTAP storage?

Yes. As long as you have discovered the on-prem ONTAP cluster as a working environment in Cloud Manager, you can scan any of the volume data.

Alternatively, you can run compliance scans on backup files created from your on-prem ONTAP volumes. So if you're already creating backup files from your on-prem systems using link:task_backup_from_onprem.html[Cloud Backup^], you can run compliance scans on those backup files.

link:task_getting_started_compliance.html[Learn more^].

== Can Cloud Compliance send notifications to my organization?

Yes. In conjunction with the Highlights feature, you can send email alerts to Cloud Manager users (daily, weekly, or monthly) when a highlight return results so you can get notifications to protect your data. Learn more about link:task_managing_highlights.html#controlling-your-data-using-highlights[highlights^].

You can also download status reports from the Investigation page in .CSV format that you can share internally in your organization.

== Can I customize the service to my organization’s needs?

Cloud Compliance provides out-of-the-box insights to your data. These insights can be extracted and used for your organization's needs.

Additionally, you can use the *Data Fusion* capability to have Cloud Compliance scan all your data based on criteria found in specific columns in databases you are scanning -- essentially allowing you to make your own custom personal data types.

link:task_managing_data_fusion.html#creating-custom-personal-data-identifiers-from-your-databases[Learn more^].

== Can Cloud Compliance work with the AIP labels I have embedded in my files?

Yes. You can manage AIP labels in the files that Cloud Compliance is scanning if you have subscribed to link:https://azure.microsoft.com/en-us/services/information-protection/[Azure Information Protection (AIP)^]. You can view the labels that are already assigned to files, add labels to files, and change existing labels.

link:task_managing_highlights.html#categorizing-your-data-using-aip-labels[Learn more^].

== Can I limit Cloud Compliance information to specific users?

Yes, Cloud Compliance is fully integrated with Cloud Manager. Cloud Manager users can only see information for the working environments they are eligible to view according to their workspace privileges.

Additionally, if you want to allow certain users to just view Cloud Compliance scan results without having the ability to manage Cloud Compliance settings, you can assign those users the _Cloud Compliance Viewer_ role.

link:concept_cloud_compliance.html#user-access-to-compliance-information[Learn more^].
