---
sidebar: sidebar
permalink: eula_fluid.html
keywords: network, connection, connectivity, kubernetes, baremetal, bare metal, bare-metal, hybrid cloud, megaport, pccw, console connect, equinix, fabric
summary: FLUID is an orchestration and automation service, integrated with Cloud Manager, that deploys bare metal kubernetes clusters and provides network connectivity to connect public, private and on-premises cloud infrastructures to create ture hybrid cloud architectures. FLUID builds the network connectivity from anywhere to anywhere seemlessly by configuring network switches, elastic cross connects and cloud provider networking APIs. FLUID can automatically build bare-metal kubernetes clusters on any compute hardware (or in virtual machines), ready for NetApp data services and other containers and virtual machine workloads to be deployed by users. FLUID can replace VMware where virtual machines are required.
---

= End User License Agreement
== Fluid
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Please read this End User License Agreement (“this Agreement”) carefully before clicking the “I agree” button below.  By clicking the “I agree” button, you are agreeing to be bound by the terms of this Agreement.  If you do not agree with the terms of this Agreement, please do not click “I agree” and instead contact us to notices@fluidhq.io 

This Agreement is between ANDREW SJOQUIST ENTERPRISES PTY LTD ABN 99 095 082 492 of Suite 301, 44 Hampden Road, Artarmon in the State of New South Wales (“ASE”) and you (“the Licensee”).  ASE owns FLUID, and agrees to grant to the Licensee the non-exclusive, non-transferable right to use Fluid, in accordance with the terms and conditions contained in this Agreement. 


== 1.1  Definitions

(1)	Authorised User means any person that has been issued an Named User Licence by ASE;

(2)	Commencement Date means the earlier of:

	(i)	the date specified in the Schedule; or

	(ii)	the date when ASE first provides the Licensee with access to any part of Fluid, pursuant to the terms of this Agreement,


(3)	Documentation means any documents, templates and/or reports that are supplied by ASE in relation to Fluid; 

(4)	Fluid means the software toolset that acts as the networking layer between NetApp (or such other third party resource) and public and private cloud;

(5)	Group means ASE and all its Related Entities and Associates (as those terms are defined in the Corporations Act 2001 (Cth);

(6)	Intellectual Property means all intellectual property rights, which arise by operation of contract, legislation, common law or equity, and which includes, but is not limited to trade marks, copyright, patents, patents pending, know how, trade secrets, names of domains, products, brands and services, moral rights, designs, inventions, internet sites and software (and in the case of ASE includes Fluid and the Documentation) 

(7)	Licence Fee means all fees charged in accordance with any other Agreement which refers to this End User License Agreement. 

(8)	Losses means any liabilities, claims, actions, suits, proceedings, judgments, losses, damages, costs and expenses which arise from this Agreement, but excludes legal and other expenses incurred in connection with a claim for which one party seeks indemnification from the other;

(9)	Named User Licence means the username and password (or other means of authentication provided by ASE from time to time) to enable access to Fluid; 

(10)	Performance Incident means: 

	(i)	any irregularity, error, problem or defect resulting from an incorrect functioning of Fluid if such irregularity, error, problem or defect renders Fluid incapable of meeting the material specifications causes incorrect functions to occur; or

	(ii)	an incorrect or incomplete identification, statement, representation or diagram in the Documentation that causes the Documentation to be inaccurate or incomplete in any material respect; 

(11)	Software Collaboration means the integration of Fluid with NetApp and any other open-source software such as:
 - Go:
    - github.com/davecgh/go-spew/spew
    - github.com/gcla/gowid
    - github.com/gdamore/encoding
    - github.com/gdamore/tcell
    - github.com/go-kit/kit/log
    - github.com/go-logfmt/logfmt
    - github.com/go-logr/logr
    - github.com/gogo/protobuf
    - github.com/golang/gddo/httputil/header
    - github.com/golang/protobuf
    - github.com/google/gofuzz
    - github.com/googleapis/gnostic
    - github.com/gorilla/mux
    - github.com/hashicorp/golang-lru
    - github.com/helloyi/go-sshclient
    - github.com/imdario/mergo
    - github.com/json-iterator/go
    - github.com/justinas/alice
    - github.com/lucasb-eyer/go-colorful
    - github.com/mattn/go-runewidth
    - github.com/mdlayher/devlink
    - github.com/modern-go/concurrent
    - github.com/modern-go/reflect2
    - github.com/mostlygeek/arp
    - github.com/namsral/flag
    - github.com/pin/tftp
    - github.com/pkg/errors
    - github.com/sirupsen/logrus
    - github.com/spf13/pflag
    - github.com/vishvananda/netlink
    - github.com/vishvananda/netns
    - golang.org/x/crypto
    - golang.org/x/net
    - golang.org/x/oauth2
    - golang.org/x/sys
    - golang.org/x/sys/unix
    - golang.org/x/text
    - golang.org/x/time/rate
    - google.golang.org/protobuf
    - gopkg.in/inf.v0
    - gopkg.in/yaml.v2
    - gopkg.in/yaml.v3
    - k8s.io/api
    - k8s.io/apimachinery
    - k8s.io/client-go
    - k8s.io/klog/v2
    - k8s.io/utils/integer
    - sigs.k8s.io/structured-merge-diff/v4/value
    - sigs.k8s.io/yaml
 - NodeJS:
    - @aws-sdk/client-direct-connect
    - @aws-sdk/client-sts
    - @azure/arm-network
    - @azure/arm-resources
    - @azure/arm-subscriptions
    - @azure/ms-rest-nodeauth
    - bull
    - class-transformer
    - class-validator
    - config
    - cors
    - express
    - flat
    - form-data
    - googleapis
    - got
    - ioredis
    - ip-cidr
    - jsonwebtoken
    - jwks-rsa
    - lodash
    - mongodb
    - mysql2
    - node-dependency-injection
    - node-forge
    - reflect-metadata
    - sequelize
    - tough-cookie
    - uuid
    - winston
    - ws
    - yaml

(12)	Third-Party Application means any product, service, system, application and/or internet site integrated or interfaced with Fluid that is owned or operated by a Third-Party Provider; 

(13)	Third-Party Licensor means any third party that licenses or otherwise conveys to ASE the right to use, distribute or make available any component of Fluid or any other data, services, software or other materials; 

(14)	Third-Party Provider means any third party that provides support, business, technology and/or other products or services which may be used in conjunction with Fluid; and

(15)	User Manual means written guidelines and/or instructions relating to Fluid.


== 2. LICENCE
*2.1 GRANT*

ASE grants the Licensee, and the Licensee accepts, the non-exclusive, non-transferable right to access and use Fluid subject to the terms of this Agreement and subject to payment of the License Fee.

	
*2.2	SCOPE AND RESTRICTIONS*

(a)	The Licensee shall only access and use Fluid:

	(i)	for business purposes, as disclosed to ASE; 

	(ii)	in accordance with the intended use of Fluid; and

	(iii)	in accordance with ASE’s instructions from time to time.


(b)	The Licensee must not, without ASE’s prior written consent:
	(i)	use Fluid for any purpose or in any manner other than as set out in this Agreement;

	(ii)	use Fluid in any way that could damage the reputation of ASE or the goodwill or other rights associated with Fluid;

	(iii)	permit any entity that is not an Authorised User to use, access or otherwise deal with Fluid;

	(iv)	reproduce, make error corrections or otherwise modify or adapt Fluid or create any derivative works based on Fluid;

	(v)	resell, sublicense, distribute, allow access to or otherwise provide or make available for any purpose any component of Fluid to any person, firm or entity that is not licensed under this Agreement;

	(vi)	attempt to disassemble, decompile, circumvent any technological measure that effectively controls access to, or reverse engineer Fluid, or otherwise engage in any conduct designed or intended to interfere with the operation of Fluid, except to the extent that such activity is expressly permitted by applicable law; or

	(vii)	modify, alter, translate, reverse engineer or create derivative works based upon Fluid. 


*2.3	NON-EXCLUSIVE*

The Licensee acknowledges that this Agreement does not grant the Licensee any exclusivity in respect of Fluid and that ASE is entitled to license Fluid to other entities in its absolute discretion. 

*2.4	THIRD-PARTY APPLICATIONS AND PROVIDERS*

(a)	The Licensee acknowledges and agrees that: 

	(i)	in order to obtain certain functions within Fluid, the Licensee may elect to obtain a licence to Third-Party Applications;

	(ii)	ASE may, with the Licensee’s prior consent, sign the Licensee up to use certain Third-Party Applications;

	(iii)	any Third-Party Applications are separate from and independent of ASE;

	(iv)	the Licensee is responsible for adhering to the terms of any agreement between the Licensee and any Third-Party Provider;

	(v)	in the event that the Licensee fails to comply with this clause, the Licensee acknowledges that the functionality of Fluid may be reduced or otherwise affected;

	(vi)	ASE makes no representations or warranties relating to, and is not liable in relation to, Third-Party Applications, or any other product, service, internet site, or other functionality operated or supplied by Third- Party Providers or any data or information provided by any of them, including, but not limited to representations or warranties as to any Third-Party Provider's compliance with laws and representations or warranties as to site availability; and

	(vii)	such Third-Party Providers and ASE are not partners, representatives or agents of each other.

(b)	In no event shall ASE be responsible for any information contained in a Third-Party Application, including without limitation, its formatting, screening or display of data, or for the Licensee's use of or inability to use such Third-Party Application. 

(c)	ASE and its Third-Party Licensors make no representations or warranties regarding:

	(i)	the availability or timing of any availability of any interface between Fluid and any third-party software and/or systems (including the Third-Party Applications); and

	(ii)	the availability of or access to or by any specific provider of third-party software and/or systems (including the Third-Party Applications).


(d)	The Licensee acknowledges and agrees that:

	(i)	in the event that the Third-Party Application is no longer available to be interfaced with Fluid, the functionality, speed or other characteristic of Fluid may be reduced or otherwise affected; and

	(ii)	ASE and its Third-Party Licensors will in no way be responsible for any Losses that may result from the Licensee's use of any Third-Party Application, despite the fact that any such Third-Party Application may interface with Fluid, or that ASE may have provided installation or integration services with respect to the same. 

==3.	LICENSEE OBLIGATIONS

*3.1	AUTHORISED USERS AND NAMED USER LICENCES*

(a)	The Licensee acknowledges that one (1) Named User Licence must only be used by one (1) Authorised User.

(b)	The Licensee's access to Fluid is dependent upon a security access system that requires each Authorised User to use their Named User Licence. 

(c)	The Licensee represents and warrants that it is authorised to receive an Named User Licence and access and use Fluid, and possesses all licenses, certifications and other authorisations, whether required by applicable law or otherwise, to effect the transactions for which the Licensee accesses and uses Fluid.

	
*3.2	INTELLECTUAL PROPERTY*
(a)	ASE remains the owner or licensee of any Intellectual Property created or developed as a result of the use of the License granted in this Agreement, and the Licensee must take all reasonable actions to protect the Intellectual Property rights comprised in Fluid. 

(b)	The Licensee will not use, replicate, or modify ASE’s Intellectual Property save for the express purpose of using Fluid for its intended purpose only pursuant to this Agreement.


*3.3	PERFORMANCE INCIDENT REPORTING AND AUDIT RIGHTS*

(a)	The Licensee agrees to provide ASE with data, documentation or other such evidence of Performance Incident(s) that it experiences during the term of the Agreement promptly upon becoming aware of such Performance Incident(s). 

(b)	ASE shall have the right, upon reasonable notice to Licensee, to audit the Licensee's use of Fluid (by means of remote access or through entry to the Licensee's premises), and Licensee agrees to allow ASE or its representatives access to such systems, facilities, books and records as are reasonably required to audit the Licensee's compliance with the Agreement. 

*3.4	COMPLIANCE WITH LAW*

(a)	Both parties will use their best endeavours to ensure compliance with: 

	(i)	all federal, state and local laws, rules, and regulations applicable to its activities in connection with which Fluid, and any data generated by, submitted to or evaluated utilising Fluid; and 

	(ii)	all applicable laws, rules, regulations and conventions relating to data privacy, data security, international communications, communications decency and the importation and exportation of software and data. 


==4.	TERMINATION

*4.1	BREACH BY LICENSEE*
	
ASE may terminate this Agreement in the event that the Licensee has breached a term of this Agreement that is not a reason referred to in Clause 4.2, and the Licensee has failed to rectify the breach within seven 7 of receiving written notice from ASE.


*4.2	SPECIAL CIRCUMSTANCES*
	
ASE may terminate the Agreement, effective immediately, in the event: 

	(i)	of any suspected breach of the Licensee’s obligations in this Agreement relating to ASE’s Intellectual Property;

	(ii)	if the License Fee has not been paid; 

	(iii)	any other agreement which refers to this EULA has been breached; and

	(iv)	the Software Collaboration is no longer in operation.


*4.3	UPON TERMINATION OR EXPIRATION*

(a)	Upon termination or expiration of this Agreement, the Licensee must: 

	(i)	immediately cease accessing and using Fluid; 

	(ii)	return to ASE, or destroy if requested by ASE, at the Licensee’s expense, all materials associated with ASE’s Intellectual Property and the Confidential Information, including, but not limited to, Fluid, the Documentation, marketing materials, stationery and signage; and

	(iii)	continue to comply with the continuing obligations under this Agreement. 

(b)	Upon request from ASE, the Licensee shall provide ASE with prompt written certification of its compliance with this clause, executed by a duly authorised officer of the Licensee. 

==5.	INDEMNITY

(a)	Notwithstanding the remainder of this Agreement, the Licensee shall indemnify and hold harmless ASE, the Group and its officers, employees and directors,  from and against any all claims, demands, Losses, damages, proceedings, compensation, Costs, charges, expenses and liabilities which may arise in respect of: 

	(i)	the Licensee's use of Fluid (except to the extent that it can be proven by the Licensee that the loss or damage was caused by the negligence or gross wilful omission of ASE); 

	(ii)	any fraudulent or unlawful acts or omissions of the Licensee in connection with the Agreement or Fluid (except to the extent that ASE or its Third-Party Licensors caused such Losses); and/or

	(iii)	any breach of any Intellectual Property clauses of this Agreement.

==6.	LIABILITY AND WARRANTIES

*6.1	DISCLAIMER*

(a)	Notwithstanding anything herein to the contrary, ASE specifically does not warrant that: 

	(i)	Fluid or any components thereof will perform without interruption or error, or that all Performance Incidents will be corrected;

	(ii)	Fluid (including the data and other information contained therein) will meet the Licensee's requirements; 

	(iii)	Fluid will operate in the configuration which the Licensee may select for use; or 

	(iv)	data or other information generated by or contained in Fluid will be accurate or complete. 

(b)	The Licensee agrees that ASE shall not be liable for:

	(i)	the accurate or complete transmission of data or other materials; 

	(ii)	any disruption, interference with, or interruption to, the Licensee’s access to Fluid;

	(iii)	any corruption or loss of the Licensee’s Intellectual Property, which is at the Licensee’s risk at all times; 

	(iv)	any Losses which the Licensee has suffered or may suffer in relation to ASE exercising its rights under this Agreement, including but not limited to pursuant to clause 10;

	(v)	any irregularities, errors, problems or defects arising from: 

		(A)	failure of Licensee to provide a suitable installation and operating environment, including but not limited to, failure to use supplies, materials, software and hardware platforms that meet the specifications set forth in the Documentation; 

		(B)	the Licensee's incorporation, attachment or engagement of any attachment, feature, program or device to Fluid; 

		(C)	use of Fluid outside the scope of its intended purpose, as described in the User Manual or ASE’s directions from time to time; or 

		(D)	the Licensee's failure to incorporate any update in usage instructions, as set out in the User Manual or otherwise, as specified previously released by ASE that corrects such item. 

(c)	ASE reserves the right to: 

	(i)	modify Fluid or substitute any materials contained therein so long as the new materials do not materially affect the functionality of Fluid; and 

	(ii)	discontinue the licensing and/or support of Fluid. 
	
*6.2	LIMITATION*
	
(a)	In no event shall ASE or its respective affiliates, partners, officers, employees, directors, agents, contractors, representatives, successors or assigns, as such, be liable to the Licensee or anyone claiming under or through the Licensee, for any punitive, exemplary, incidental, indirect, or special damages, or consequential loss, based on, arising out of or in connection with this Agreement, or any matter relating to this Agreement, or error in information (whether negligent or not) supplied before or after the date of this Agreement in connection with its subject matter, whether based on contract, tort (including but without limitation negligence), or any other legal or equitable grounds, even if ASE knew or ought to have known of the possibility of such damages or consequential loss. ‘Consequential loss’ shall include but not be limited to loss of profits, interest revenue, use, or goodwill (or similar financial loss), loss of data, business interruption, or payments made or due to any third party.


==7.	NOTICES

Unless otherwise specified in the Agreement, all notices, requests, demands, and other communications (other than routine operational or billing communications) required or permitted hereunder shall be in writing and shall be deemed to have been received by a party one (1) business day after transmission by electronic mail.

==8.	SEVERABILITY

If anything in this Agreement is deemed to be unenforceable, illegal or void, then it is severed and leaves intact all other non-severable parts of this Agreement, which remain in full force.

==9.	GOVERNING LAW 

(a)	This Agreement will be governed by and construed in accordance with the laws from time to time in force in the state of New South Wales and both parties submit to the non-exclusive jurisdiction of the courts of that state and of the Commonwealth of Australia.
